### ISSUE TITLE
Protocol error using js8call and wsjtx

### ISSUE THREAD

**Issue by Jehreg** [nonoo/kappanhang#9]
Running kappanhang commit a998382
Raspberry pi 4
Go installed from binaries and resides in /usr/local/go/bin
go version go1.15.6 linux/arm
Connecting to a ICOM-705 on 192.168.88.186
./go/bin/kappanhang -a 192.168.88.186 -u <user> -p <password>
...many good output lines...
... I start js8call version 2.2.0 or wsjtx version 2.2.2
2020-12-26T10:06:53.563-0500    error   rigctld@409: got unknown cmd POST /RPC2 HTTP/1.1
2020-12-26T10:06:53.563-0500    error   rigctld@409: got unknown cmd User-Agent: XMLRPC++ 0.8
2020-12-26T10:06:53.563-0500    error   rigctld@409: got unknown cmd Host: 127.0.0.1:12345
2020-12-26T10:06:53.563-0500    error   rigctld@409: got unknown cmd Content-type: text/xml
2020-12-26T10:06:53.564-0500    error   rigctld@409: got unknown cmd Content-length: 89
2020-12-26T10:06:53.564-0500    info    rigctld: client 127.0.0.1:42108 disconnected
panic: runtime error: index out of range [0] with length 0 rfg 65% sql 19%
2020-12-26T10:06:53.742-0500   S0    10.130720 TS1 USB 8.1V txpwr 6%
goroutine 39 [running]:-0500 up   1m5s rtt   5ms up    951 B/s down 100.0 kB/s retx  1 /1m lost 0/1m
main.(*rigctldStruct).processCmd(0x3371d0, 0x31b3b0, 0x0, 0x0, 0x0, 0x0)
	/home/pi/go/src/github.com/nonoo/kappanhang/rigctld.go:138 +0x15f8
main.(*rigctldStruct).clientLoop(0x3371d0)
	/home/pi/go/src/github.com/nonoo/kappanhang/rigctld.go:407 +0x2d8
created by main.(*rigctldStruct).loop
	/home/pi/go/src/github.com/nonoo/kappanhang/rigctld.go:440 +0x2c

I will get this error even if I set -s 12345

My ICOM-705 firmware is version 1.12

**Comment by nonoo** [comment]
Some app is trying to send a HTTP request to the rigctld port of kappanhang. The rigctld port will only handle rigctl commands (there's no HTTP request support). You can change the rigctld port with -r, not with -s.
